[platformio]
default_envs = esp8266clone
;default_envs = d1_mini

[common]
lib_ldf_mode = deep
; Monitor-Einstellungen
monitor_speed = 115200
; RTS/DTR für Auto-Reset (wichtig für Clones!)
monitor_dtr = 1
monitor_rts = 1

monitor_filters = 
    default
    time
    esp8266_exception_decoder

[env]
framework = arduino
platform = espressif8266

; Bibliotheken
lib_deps = 
    fastled/FastLED @ ^3.6.0
    adafruit/RTClib @ ^2.1.1        ; NEU: RTC-Bibliothek

;|-- DNSServer @ 1.1.1
;|-- EEPROM @ 1.0
;|-- ESP8266WebServer @ 1.0
;|-- ESP8266WiFi @ 1.0
;|-- Wire @ 1.0

; Build-Flags für Debug
build_flags =
    -I include
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DDEBUG_ESP_PORT=Serial
    -DDEBUG_ESP_CORE=false
    -DDEBUG_MODE=false  ;true = Debug, false = Produktiv
    -DNDEBUG
    -DDEBUG_SOURCE=true
    -DDEBUG_ESP_WIFI=0
    -DUSE_RTC=true
    -DTEST_RGB_ONLY=false
    -DTEST_RGB=false
    -DTEST_ALLTHETIME=false
    -DPOWERLOSSDETECT=false
    -DCHARGRAPH_DEBUG

; Monitor-Einstellungen
monitor_filters = 
    default
    time
    esp8266_exception_decoder

extra_scripts = pre:html_to_header.py

[env:esp8266clone]
board = esp12e                     ; ESP8266MOD = ESP-12E/F kompatibel
framework = ${env.framework}
platform = ${env.platform}

; Serial-Einstellungen
monitor_speed = ${common.monitor_speed}

upload_speed  = 115200              ; Langsam für Clone-Stabilität
;upload_port = COM13

; Flash-Einstellungen (sicher für alle Clones)
board_build.flash_mode = dio       ; Statt qio - kompatibler!
# CPU-Frequenz auf 160MHz erhöhen
board_build.f_cpu = 160000000L
; Flash-Einstellungen (4MB Flash für Standard D1 Mini)
board_build.f_flash = 40000000L
board_build.ldscript = eagle.flash.4m2m.ld ;2 MB Sketch, 2 MB OTA kein SPIFFS

; Build-Flags für Debug
build_flags = 
    ${env.build_flags}
    ;-DBRIDGE_LEDS_POS77

; Bibliotheken
lib_deps = ${env.lib_deps}

; Monitor-Einstellungen
monitor_filters = ${common.monitor_filters}
    
; RTS/DTR für Auto-Reset (wichtig für Clones!)
monitor_dtr = 1
monitor_rts = 1

[env:d1_mini]
board = d1_mini
platform = ${env.platform}
framework = ${env.framework}

; Serial-Einstellungen
monitor_speed = ${common.monitor_speed}

; Upload-Einstellungen
;upload_speed = 921600
upload_speed = 115200
;upload_port = COM13              ; Automatische Erkennung oder manuell anpassen
;upload_port = COM5

board_build.flash_mode = dio
# CPU-Frequenz auf 160MHz erhöht
board_build.f_cpu = 160000000L  ; Statt 80000000L
; Flash-Einstellungen (4MB Flash für Standard D1 Mini)
board_build.f_flash = 40000000L
board_build.ldscript = eagle.flash.4m2m.ld

; Build-Flags für Debug
build_flags = 
    ${env.build_flags}
    ;-DBRIDGE_LEDS_POS77

; Bibliotheken
lib_deps = ${env.lib_deps}

; Monitor-Einstellungen
monitor_filters = ${common.monitor_filters}
